# Generated by Django 3.2.7 on 2023-01-06 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='categories/images/', verbose_name='Основная картинка')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна ли категория?')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('image', models.ImageField(upload_to='product/main/images/', verbose_name='Основная картинка')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии?')),
                ('price', models.CharField(max_length=127, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('image', models.ImageField(upload_to='product_auto/main/images/', verbose_name='Основная картинка')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии?')),
                ('power_reserve', models.CharField(max_length=127, verbose_name='Запас хода')),
                ('battery_capacity', models.CharField(max_length=127, verbose_name='Ёмкость батареи')),
                ('price', models.CharField(max_length=127, verbose_name='Цена')),
                ('torque', models.CharField(max_length=127, verbose_name='Крутящий момент')),
                ('max_speed', models.CharField(max_length=127, verbose_name='Максимальная скорость')),
                ('type_body', models.CharField(max_length=127, verbose_name='Тип кузова')),
                ('type_drive', models.CharField(choices=[('FRONT', 'Передний'), ('BACK', 'Задний'), ('FULL', 'Полный'), ('AWD', 'AWD')], default='Передний', max_length=127, verbose_name='Тип привода')),
                ('mileage', models.CharField(max_length=127, verbose_name='Пробег')),
                ('year_issue', models.PositiveIntegerField(default=2020, verbose_name='Год выпуска')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_auto', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт (Транспорт)',
                'verbose_name_plural': 'Продукты (Транспорт)',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/more/images/', verbose_name='Доп. картинка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAutoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_auto/more/images/', verbose_name='Доп. картинка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productauto')),
            ],
        ),
    ]
