# Generated by Django 3.2.7 on 2023-01-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='company_info/logo/image/', verbose_name='Логотип')),
                ('about_image', models.ImageField(upload_to='company_info/about/image/', verbose_name='Картинка в блок "о нас"')),
                ('about_image2', models.ImageField(upload_to='company_info/about/image/', verbose_name='Картинка в блок "о нас"')),
                ('about_image3', models.ImageField(upload_to='company_info/about/image/', verbose_name='Картинка в блок "о нас"')),
                ('text', models.TextField(verbose_name='О нас (Описание)')),
                ('phone_number', models.CharField(max_length=127, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('telegram', models.URLField(verbose_name='Ссылка на telegram')),
                ('whatsapp', models.URLField(verbose_name='Ссылка на whats app')),
                ('instagram', models.URLField(verbose_name='Ссылка на instagram')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компания',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company_info/slider/images/', verbose_name='Картинки для слайдера')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='company_info.companyinfo')),
            ],
        ),
    ]
